name: LTD Workflow
on:
    workflow_dispatch:
  
jobs:
  ltd-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: LintCode
        run: |
          echo "Running lint"
          echo "Dinesh Test completed successfully"
