#Test workflow
name: test-workflow
on:
  workflow_dispatch:
jobs:
  myfirst-job:
    runs-on: ubuntu-latest
    defaults:  
      run:
        working-directory: ./PracticeProj-1
    steps:
      - name: DownloadCode
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22'
      
      - name: TestStage-start
        run: |
          echo "Starting test"
      - name: InstallDependencies
        run: |
          npm install
          echo "Dependencies installed"
      - name: RunLint
        run: |
          npm run lint
          echo "Linting completed"
      - name: RunTests
        run: |
          npm test
          echo "Tests completed"

      - name: Buildapp
        run: |
          npm run build
          echo "Build completed successfully"



