name: test-workflow
on:
  workflow_dispatch:
jobs:
  myfirst-job:
    defaults:  
      run:
        working-directory: ./PracticeProj-1
    runs-on: ubuntu-latest
    steps:
      - name: TestStage-start
        run: |
          echo "Starting test"
      - name: DownloadCode
        uses: actions/checkout@v6
      - name: InstallDependencies
        run: |
          npm install
          echo "Dependencies installed"
      - name: RunLint
        run: |
          npm run lint
          echo "Linting completed"
      - name: RunTests
        run: |
          npm test
          echo "Tests completed"



